# action.yml

name: 'WIPAC Dev Mongo Versions'
description: 'GitHub Action Package for Generating a Build Matrix of Supported MongoDB Versions'

inputs:
  mongo_min:
    description: 'Minimum MongoDB version to include (inclusive). Default is 4.0'
    required: false
    default: '4.0'
  mongo_max:
    description: 'Maximum MongoDB version to include (inclusive). Default is the latest MongoDB version.'
    required: false
    default: ''
  mongo_exclude:
    description: 'Comma-separated list of MongoDB versions to exclude from the matrix (e.g., "5.0,6.0").'
    required: false
    default: ''

outputs:
  matrix:
    description: "List of Supported MongoDB Versions"
    value: ${{ steps.gather-mongo-versions.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - id: gather-mongo-versions
      run: |
        set -euo pipefail
        echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"

        python3 -m venv action_venv
        . action_venv/bin/activate
        pip3 install --upgrade pip
        pip3 install -r ${{ github.action_path }}/requirements.txt

        export GHA_INPUT_EXCLUDE="${{ inputs.mongo_exclude }}"
        export GHA_INPUT_MAX="${{ inputs.mongo_max }}"
        export GHA_INPUT_MIN="${{ inputs.mongo_min }}"
        export GHA_INPUT_OMIT_RC="${{ inputs.omit_prerelease }}"

        MATRIX=$( "${{ github.action_path }}/generate_matrix.py" )
        echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"

      shell: bash
